# Generated by Django 4.0.2 on 2022-02-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_brevaluation_mean_br_player_reward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brevaluation',
            name='mean_br_player_reward',
        ),
    ]
