# Generated by Django 4.0.2 on 2022-12-03 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_experiment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brevaluation',
            name='checkpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.equilibriumsolverruncheckpoint'),
        ),
    ]
